apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs-watcher
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-jobs-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-watcher
subjects:
- kind: ServiceAccount
  name: orchestrator
  namespace: default
