apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jobs-watcher-binding
subjects:
- kind: ServiceAccount
  name: orchestrator
  namespace: default
roleRef:
  kind: Role
  name: jobs-watcher
  apiGroup: rbac.authorization.k8s.io