NAMESPACE = "default"
DOCKER_HUB_NAME = "setin"

ZOOKEEPER_NAME = "zookeeper"
ZOOKEEPER_PORT = "2181"
ZOOKEEPER_TICK_TIME = "2000"

BROKER_NAME = "kafka-broker"
BROKER_PORT = 9092
BROKER_VOLUME_NAME = "kafka-storage"

DATABASE_NAME = "database"
DATABASE_PORT = 5432
DATABASE_VOLUME_NAME = "database-volume"

KAFKA_BOOTSTRAP_SERVERS = "kafka-broker:9092"
KAFKA_ZOOKEEPER_CONNECT = "zookeeper:2181"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_HOST = "database:5432"
POSTGRES_NAME = "postgres"
