apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: service3:latest # specify the local Docker image
        env:
        - name: SERVICE_NAME
          value: "service3"
        - name: KAFKA_TOPIC
          value: "resources"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "[localhost:9092]"
        - name: POSTGRES_HOST
          value: "localhost:5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
