apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: setin/service1/service1:latest
        command: ["python", "/app/service1.py"]
        envFrom:
        - configMapRef:
            name: service1-config
      - name: resource-monitor
        image: resource-monitor:latest
        command: ["python", "/app/resource-monitor/resource_monitor.py", "service1"]
        envFrom:
        - configMapRef:
            name: service1-config