apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: service2:latest # specify the local Docker image
        env:
        - name: SERVICE_NAME
          value: "service2"
        - name: KAFKA_TOPIC
          value: "resources"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "[localhost:9092]"
        - name: POSTGRES_HOST
          value: "localhost:5432"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
